name: Test Automated Report

on:
  schedule:
    - cron: "*/15 * * * *"   
  workflow_dispatch:       

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Write Gmail credentials
        run: echo "${{ secrets.GMAIL_CREDENTIALS }}" > credentials.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          export PATH=$PATH:/usr/bin

      - name: Run script
        run: python main.py
